const express = require('express');
const cors = require('cors');
const multer = require('multer');
const app = express();
const PORT = process.env.PORT || 3000;
app.use(cors({ origin:'*', methods:['GET','POST','OPTIONS'], allowedHeaders:['Content-Type','Authorization'] }));
app.use(express.json({ limit:'1mb' }));
app.get('/', (req, res) => res.json({ status:'ok', service:'Decode API' }));
app.use('/api/analyze', require('./api/analyze'));
app.use('/api/chat', require('./api/chat'));
app.use('/api/ask', require('./api/ask'));
app.use('/api/listen', require('./api/listen'));
app.listen(PORT, () => console.log(`Decode API running on port ${PORT}`));
